---
title: "Fanpage de U2"
author: "Natalie"
date: 26
format: html
editor: visual
---

### Biografía de U2

Todo comenzó en 1976 cuando Larry Mullen colgó un anuncio de "se buscan músicos" en el tablón de anuncios de la escuela Temple Mount de Dublín: "Baterista busca músicos para formar una banda". "Así que el sábado 25 de septiembre de 1976", recuerda Larry, "este peculiar grupo de personas se reunió en mi cocina en Artane. Y ahí empezó todo".

Adam Clayton había descubierto el rock and roll a los trece años, comprando su primera guitarra acústica y luego convenciendo a sus padres para que le compraran un bajo. "Simplemente me sonaba bien. Profundo, potente y satisfactorio".

Desde sus inicios, U2 se caracterizó por su pasión. "Éramos una banda antes de saber tocar", así lo expresó Bono en sus primeras entrevistas. Edge recuerda leer semanalmente las revistas musicales británicas NME y Sounds, y luego oír hablar de ese "chico salvaje llamado Paul Hewson".

Los cuatro adolescentes, que inicialmente se hacían llamar 'Feedback', ensayaban en la cocina de Larry en Dublín: Bono en la voz, The Edge en la guitarra, y Adam Clayton y Larry formaban la sección rítmica de bajo y batería. Inspirados por el punk, pero protegidos de la frialdad distante que les brindaba el mar de Irlanda, Feedback se había convertido en 'The Hype' y luego en 'U2', y pronto se labraron una reputación local basada en la pasión de sus actuaciones.

«Supongo que un momento decisivo fue ver a The Jam en Top of the Pops», recuerda 'Edge'. «Y darnos cuenta de que, en realidad, no saber tocar no era un problema... la música se trataba más de energía y de intentar decir algo, y no necesariamente de una gran maestría musical».

Tras un breve periodo siendo representados por Adam, se reunieron con Paul McGuinness, pero un lanzamiento temprano en Irlanda en 1979, el EP 'U23' en CBS, resultó ser un éxito aislado. Tuvieron que esperar hasta el año siguiente para firmar un contrato a largo plazo con Island Records, el sello de Chris Blackwell. «Me asombró la calidad, el talento y la ambición de estos cuatro músicos, y aun así no conseguimos un contrato discográfico», recuerda McGuinness. «Todo el mundo rechazó a U2 antes de que finalmente encontráramos nuestro lugar en Island Records » .
